const ENV = process.env;

module.exports = {
  NODE_ENV: ENV.NODE_ENV,
  APP_PORT: ENV.APP_PORT,
  TOKEN_DEV: ENV.TOKEN_DEV,
  TOKEN_PROD: ENV.TOKEN_PROD,
  WEBHOOK_PATH: ENV.WEBHOOK_PATH,
  WEBHOOK_PORT: ENV.WEBHOOK_PORT,
  WEBHOOK_URL: ENV.WEBHOOK_URL,
  URL_DB: ENV.URL_DB,
  AWS_ACCESS_KEY: ENV.URL_DB,
  AWS_SECRET_ACCESS_KEY: ENV.URL_DB,
  AWS_REGION: ENV.URL_DB,
  PROJECT_ID: ENV.PROJECT_ID,
  SESSION_ID: ENV.SESSION_ID,
  PRIVATE_KEY: ENV.PRIVATE_KEY,
  CLIENT_EMAIL: ENV.CLIENT_EMAIL,
};
